name: quan_li_cong_viec
description: "Ứng dụng quản lý quán cafe chuyên nghiệp"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Thư viện SQLite gốc (Cho Android/iOS)
  sqflite: ^2.3.0

  # THƯ VIỆN THIẾU: Để chạy được trên Windows/Desktop
  sqflite_common_ffi: ^2.3.3

  path: ^1.9.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true